### ISSUE TITLE
Alternative / replacement syntax for generating utilities (just placeholders for now, more utility types later!)

### ISSUE THREAD

**Issue by burntcustard** [wearelighthouse/stemCSS#17]
As an extension to the 'Generate placeholder ranges for all breakpoints for everything' #16 discussion (which could maybe be locked as this kind of continues from it)...

I'm suggesting a new way of writing utilities for stemCSS. Right now focused on placeholders, but spreading to anything else a utility should be able to create in the future (classes?)

Right now, utilities sit in the /settings/ folder, and they add themselves to the $make-utilities list, and then [/utilities/_utilities.scss](https://github.com/wearelighthouse/stemCSS/blob/master/utilities/_utilities.scss) goes through that list, and `@includes` the `makeUtilities` mixin (located in [/tools/_utilities](https://github.com/wearelighthouse/stemCSS/blob/master/tools/_utilities.scss)) for all the utilities. This isn't super important, but I want to make sure I've got my head around the current system!

Currently, utilities are defined like this (from [/settings/_utilities-position.scss](https://github.com/wearelighthouse/stemCSS/blob/master/settings/_utilities-position.scss)):
```
$utilities-position-settings: (
  (
    property: ('position', 'pos'),

    values: (
      (
        absolute,
        relative,
      ),
    ),
  ),
);
$make-utilities: append($make-utilities, $utilities-position-settings);
```

I'm suggesting a change to the way they're written, to something like:
```
@each $value in ('absolute', 'relative') {
  @include make-placeholder((
    alias: 'pos-' + $value,
    position: $value
  ));
}
```
There are more examples of utilities in my "suggested style", alongside the old style, in the [feature/auto-placeholder-gen branch](https://github.com/wearelighthouse/stemCSS/tree/feature/auto-placeholder-gen) (although those may disappear as I continue ~~breaking things~~ working on it!)

The new syntax, along with the make-placeholder function in [`_auto-placeholders.scss`](https://github.com/wearelighthouse/stemCSS/blob/feature/auto-placeholder-gen/tools/_auto-placeholders.scss) has:
### Advantages
✅ More CSS-ey, with `property: value` syntax.
✅ No crazy trails of parenthesis and commas.
✅ Allows funky values like `'calc(--var(my-css-variable)' + $i + ')'`
✅ A utility can have many properties _and_ different values for each - e.g. [`_utilities-margin.scss`](https://github.com/wearelighthouse/stemCSS/blob/feature/auto-placeholder-gen/settings/_utilities-margin.scss).
✅ Facilitates more complex creation of placeholders. See [`_utilities-gc.scss`](https://github.com/wearelighthouse/stemCSS/blob/feature/auto-placeholder-gen/settings/_utilities-gc.scss).
✅ Auto generation of each utility, at EVERY BREAKPOINT. E.g. `%u-gc-1-3:from-large-header`.
✅ Allows cleaner breakpoint use (per-property rather than group of properties within breakpoint).
✅ Allows breakpoint-related `@extend`-ing (had to use plain CSS properties before).

### Disadvantages
🛑 With "aliases" for both properties and values, things can get a bit loopy.
🛑 Is a lot of change for similar functionality.
🛑 Harder to write - need to know SASS [control directives](http://thesassway.com/intermediate/if-for-each-while).

### Side effects / other notes
⚠️ Currently only makes placeholders (not classes, so can't use in HTML).
⚠️ Currently only makes utilities ('u-' namespace), but could (should?) be used for objects as well.

**Comment by RussellBishop** [comment]
Notes for classes you'll want:

```
.u-sibling-mt-5rem > * + * {
  margin-top: 5rem;
}
```

**Comment by RussellBishop** [comment]
So we were discussing how we would selectively make classes from the big net of placeholders. A draft for how you would do that…?

```
$classes-display-settings: (
  'flex', (
    'up-to-medium',
    'from-medium-up-to-large',
  ),
  'none', (
    'from-large',
  )
);

@each $value in $classes-display-settings {
  @include make-classes((
    display: $value
  ));
}
```

It's probably worth noting that placeholder names (%thingy) use aliases – so I suppose we would also need to use those in the map to make classes out of them?

Also, you would want to be able to specify 'no-breakpoint' here too. Not sure whether to bundle those together, or have a $..responsive-settings list also.

**Comment by burntcustard** [comment]
List of things to finalise for stemCSS in the near future in relation to this issue/feature request:

1. Finalise syntax and finish off the SCSS code for automatic placeholder generation.
2. Same as above for listing breakpoints that get automatically put in the placeholders.
3. Decide on and implement how classes are created (see Russ' message above).
4. Reimplement some of the current _utilities (e.g. color) with the new system. (And the others and/or new utilities will be done as they're needed in ongoing projects, then added afterwards to stemCSS if they're useful for _most_ other projects).

**Comment by burntcustard** [comment]
On point 3 (those should have been numbered... I mean the deciding how classes are created):

On auto-placeholder-gen branch (https://github.com/wearelighthouse/stemCSS/commit/0710ef3c467e90ce6f517fec0a605c7f75c43916), instead of using a `make-placeholder()` mixin, `make-utility()` is used, e.g:

```scss
@each $name, $hex in ($global-colors) {
  @include make-utility((
    alias: 'color-' + $name,
    class: true,
    color: $hex
  ));
}
```
Where the `class: true` key-value pair indicates that not only placeholder(s) should be made, but also classes.

This decision has been made over using separate `make-placeholder()` and `make-class()` mixins, because there is little reason to make a class but not make a placeholder.

The mixins `make-placeholder()` and `make-class()` still exist, but are no longer for "consumer use" and are basically just parts of `make-utility()`. They take a utility name and a properties map.

Unfortunately because of not being able to `@extend` within `@media`, making classes at every single breakpoint is messy. It's currently commented out in `_make-utility.scss`. If un-commented-out, it works, but it creates new styles for every breakpoint (rather than extending the placeholders).
