### ISSUE TITLE
Including .25rem margin/padding utils, consider switching from `mh` to `mx`

### ISSUE THREAD

**Issue by burntcustard** [wearelighthouse/stemCSS#29]
Using `u-mx-` (margin-x-axis) and `u-my-` (margin-y-axis) rather than `u-mh-` (margin-horizontal) and `u-mv-` (margin-vertical), would make stemCSS more similar to [Bootstrap](https://getbootstrap.com/docs/4.3/utilities/spacing/) and [Tailwind CSS](https://tailwindcss.com/docs/margin/) syntax. Margin and padding utilities and/or classes, with default `.25rem` steps are common in other frameworks too, and I've been including those in most projects we've worked on recently, so those should get thrown in too (just got to decide where/what setting/s should go).

This would all be good because it'd reduce the amount of re-learning syntax for devs already used to one or any of these frameworks. Also, everybody else is doing it this way - does that mean it (`m-x/y` etc.) is right? In this case, as a lot of them are open source... I'd say yes, it probably is.

**Comment by RussellBishop** [comment]
Go to bed, John.

**Comment by burntcustard** [comment]
Maybe I am in bed :stuck_out_tongue_winking_eye: It was ages ago I thought of this - it needed writing down before I forgot! :laughing:

**Comment by burntcustard** [comment]
Switched and added in https://github.com/wearelighthouse/stemCSS/pull/32
